More BugFixing: - Fixed error when viewing inspect page with 0 bukkit servers - Fixed html caching with PostHtmlWebAPI - Fixed css serving on API mode WebServer - Fixed UUIDFetcher NoClassDefFoundError on Bungee
Notable bugs that need fixing:
- PostHtmlWebAPI html is cut short because of & or = signs