Bugfix for NoClassDefFoundError when PlanLite not installed
* Added new DataPushHook to prevent Hook from not being found.
* Added null checks for PlanLiteHook, because it was causeing NPEs